// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.M_Road = (function() {
    function M_Road(t0, t11, road) {
      this.t0 = t0;
      this.t1 = t11;
      this.road = road;
    }

    M_Road.prototype.getPosition = function() {
      return this.road.getPosition((this.t0 + t1) / 2);
    };

    return M_Road;

  })();

}).call(this);
