// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.Curve = (function() {
    function Curve() {
      this._spline = new THREE(THREE.CatmullRomCurve3());
    }

    Curve.prototype.addPoint = function(p) {
      return this._spline.points.push(p);
    };

    Curve.prototype.getPoints = function(max_length) {
      var S, high, low, output, p0, p_high, p_low, results;
      output = [];
      p0 = this._spline.getPoint(0);
      output.push(p0);
      S = [];
      S.push(1.0);
      low = 0;
      p_low = this._spline.getPoint(low);
      results = [];
      while (S.length !== 0) {
        high = S.pop();
        p_high = this._spline.getPoint(high);
        while (p_low.distanceTo(p_high) > max_length) {
          S.push(high);
          high = (low + high) / 2.0;
          p_high = this._spline.getPoint(high);
        }
        output.push(p_high);
        low = high;
        p_low = p_high;
        continue;
      }
      return results;
    };

    return Curve;

  })();

}).call(this);
