// Generated by CoffeeScript 1.11.1

/*
    Random Scene.
    Written by Bryce on 11/22/2016
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Random_Scene = (function(superClass) {
    extend(Random_Scene, superClass);

    function Random_Scene(scene_width, scene_height) {
      var h, i, j, mesh, pos, rotation, scale, w, x, y;
      Random_Scene.__super__.constructor.call(this);
      this._scale = 40;
      this._padding = 30;
      this._Mesh_Factory = new TSAG.Unit_Meshes();
      this._AABB = null;
      for (i = j = 0; j < 1000; i = ++j) {
        mesh = this._newHouse({
          color: 0xaaaaaa
        });
        x = this._padding + Math.random() * (scene_width - this._padding * 2);
        y = this._padding + Math.random() * (scene_height - this._padding * 2);
        w = this._scale;
        h = this._scale;
        pos = mesh.position;
        pos.x = x;
        pos.y = y;
        scale = mesh.scale;
        scale.x = w;
        scale.y = h;
        rotation = mesh.rotation;
        rotation.z = Math.random() * Math.PI * 2;
        this.add(mesh);
      }
      return;
    }

    Random_Scene.prototype._newHouse = function(params) {
      var node, square, triangle;
      square = this._Mesh_Factory.newSquare(params);
      triangle = this._Mesh_Factory.newTriangle(params);
      triangle.position.x = .5;
      triangle.scale.x = .5;
      node = new THREE.Object3D();
      node.add(square);
      node.add(triangle);
      return node;
    };

    Random_Scene.prototype.getMeshFactory = function() {
      return this._Mesh_Factory;
    };

    Random_Scene.prototype.queryPoint = function(x, y) {
      var aabb_line_meshes, direction, j, len, line_material, mesh, origin, ray, results;
      if (this._AABB === null) {
        this._AABB = new TSAG.AABB(this, {
          val: 'x',
          dim: 2
        });
        line_material = new THREE.LineBasicMaterial({
          color: 0x0000ff
        });
        aabb_line_meshes = this._AABB.get_AABB_line_meshes(line_material);
        for (j = 0, len = aabb_line_meshes.length; j < len; j++) {
          mesh = aabb_line_meshes[j];
          this.add(mesh);
        }
      }
      origin = new THREE.Vector3(x, y, -10);
      direction = new THREE.Vector3(0, 0, 1);
      ray = new THREE.Ray(origin, direction);
      results = this._AABB.collision_query(ray);
      return results;
    };

    return Random_Scene;

  })(THREE.Scene);

}).call(this);
