// Generated by CoffeeScript 1.11.1

/*
    Random Scene.
    Written by Bryce on 11/22/2016
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Random_Scene = (function(superClass) {
    extend(Random_Scene, superClass);

    function Random_Scene(scene_width, scene_height) {
      var h, i, j, mesh, pos, rotation, scale, w, x, y;
      Random_Scene.__super__.constructor.call(this);
      this._scale = 40;
      this._padding = 30;
      this._Mesh_Factory = new TSAG.Unit_Meshes();
      for (i = j = 0; j <= 10; i = ++j) {
        mesh = this._Mesh_Factory.newSquare({
          color: 0xaaaaaa
        });
        x = this._padding + Math.random() * (scene_width - this._padding * 2);
        y = this._padding + Math.random() * (scene_height - this._padding * 2);
        w = this._scale;
        h = this._scale;
        pos = mesh.position;
        pos.x = x;
        pos.y = y;
        scale = mesh.scale;
        scale.x = w;
        scale.y = h;
        rotation = mesh.rotation;
        rotation.z = Math.random() * Math.PI / 2;
        this.add(mesh);
      }
      return;
    }

    Random_Scene.prototype.getMeshFactory = function() {
      return this._Mesh_Factory;
    };

    return Random_Scene;

  })(THREE.Scene);

}).call(this);
