// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.Set = (function() {
    function Set() {}

    Set.prototype.add = function(object) {
      console.log("ERROR: BT2D: intersectRay. This method should be overriden.");
      return false;
    };

    Set.prototype.clear = function() {};

    Set.prototype.remove = function(object) {};

    return Set;

  })();

}).call(this);
