// Generated by CoffeeScript 1.11.1

/*
 *
 * Element Interface Class.
 * This specifies properties of all element objects.
 *
 * Written by Bryce Summers on 12 - 19 - 2016.
 *
 */

(function() {
  TSAG.E_Super = (function() {
    function E_Super(_view) {
      this._view = _view;
      if (!this._view) {
        this._view = new THREE.Object3D();
      }
      this._BVH = null;
    }

    E_Super.prototype.getVisual = function() {
      return this._view;
    };

    return E_Super;

  })();

}).call(this);
