// Generated by CoffeeScript 1.11.1

/*
 *
 * Car Element Class.
 * 
 * Written by Bryce Summers on 1 - 31 - 2017.
 *
 * Purpose: This class specifies the gameplay and aesthetic properties of building objects.
 *
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.E_Car = (function(superClass) {
    extend(E_Car, superClass);

    function E_Car(scale) {
      E_Car.__super__.constructor.call(this);
      this.createVisual(scale);
      this.distance = 0.0;
      this.segment_index = 0;
      this.next_car = null;
    }

    E_Car.prototype.createVisual = function(scale) {
      var mesh, view;
      view = this.getVisual();
      mesh = this._newCar({
        color: TSAG.style.c_car_fill
      });
      view.add(mesh);
      view.position.z = TSAG.style.dz_cars;
      return this.setScale(scale);
    };

    E_Car.prototype._newCar = function(params) {
      var mesh_factory, square;
      mesh_factory = TSAG.style.unit_meshes;
      square = mesh_factory.newSquare(params);
      square.scale.x = 2;
      return square;
    };

    return E_Car;

  })(TSAG.E_Super);

}).call(this);
