// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.E_Intersection = (function(superClass) {
    extend(E_Intersection, superClass);

    function E_Intersection(position) {
      var fill, sx, sy, view;
      E_Intersection.__super__.constructor.call(this);
      this._position = position;
      fill = TSAG.style.unit_meshes.newSquare({
        color: TSAG.style.c_road_fill
      });
      fill.position.copy(new THREE.Vector3(position.x, position.y, 0));
      sx = sy = TSAG.style.road_offset_amount * 2;
      fill.scale.copy(new THREE.Vector3(sx, sy, 1));
      view = this.getVisual();
      view.add(fill);
      view.position.z = TSAG.style.dz_intersection;
      this.generateBVH();
    }

    E_Intersection.prototype.addRoad = function(road) {
      var edge;
      edge = road.getEdge();
      return true;
    };

    E_Intersection.prototype.getPoint = function() {
      return this._position.clone();
    };

    return E_Intersection;

  })(TSAG.E_Super);

}).call(this);
