// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.E_Network = (function(superClass) {
    extend(E_Network, superClass);

    function E_Network(graph) {
      E_Network.__super__.constructor.call(this);
      this.setTopology(graph);
      this._network_processor = new SCRIB.PolylineGraphPostProcessor(graph);
      this.roads = [];
    }

    E_Network.prototype.getRoads = function() {
      return this.roads;
    };

    E_Network.prototype.query_elements_pt = function(x, y) {
      var elements, i, len, polyline, polylines;
      polylines = this._bvh.query_point_all(new BDS.Point(x, y));
      elements = [];
      for (i = 0, len = polylines.length; i < len; i++) {
        polyline = polylines[i];
        elements.push(polyline.getAssociatedData());
      }
      return elements;
    };

    E_Network.prototype.query_elements_box = function(box) {
      var elements, i, len, polyline, polylines;
      polylines = this._bvh.query_box_all(box);
      elements = [];
      for (i = 0, len = polylines.length; i < len; i++) {
        polyline = polylines[i];
        elements.push(polyline.getAssociatedData());
      }
      return elements;
    };

    E_Network.prototype.newTopology_vertex = function() {
      var graph;
      graph = this.getTopology();
    };

    return E_Network;

  })(TSAG.E_Super);

}).call(this);
