// Generated by CoffeeScript 1.11.1

/*
    SimUrban User Interface Object.
    Written by Bryce on 4.6.2017
    
    Purpose: This class organizes the drawing and functionality for all of the static user interface elements,
        such as windows, buttons, etc.

        This class also handles the text based display of information to the users.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.E_UI = (function(superClass) {
    extend(E_UI, superClass);

    function E_UI() {
      var b1, b2, b3, func_build_road_artery, func_build_road_collector, func_build_road_local, img_build_road_artery, img_build_road_collector, img_build_road_local, p1, p2;
      E_UI.__super__.constructor.call(this);
      this.controller_ui = new BDS.Controller_UI(canvas_G);
      this.controller_build_road = this.controller_build_road.setActive(false);
      this.controller_demolish_road = this.controller_demolish_road.setActive(false);
      b1 = new BDS.Box(new BDS.Point(0, 0), new BDS.Point(64, 64));
      b2 = new BDS.Box(new BDS.Point(64, 0), new BDS.Point(128, 64));
      b3 = new BDS.Box(new BDS.Point(128, 0), new BDS.Point(192, 64));
      p1 = b1.toPolyline();
      p2 = b2.toPolyline();
      func_build_road_local = function() {};
      func_build_road_collector = function() {};
      func_build_road_artery = function() {};
      img_build_road_local = null;
      img_build_road_collector = null;
      img_build_road_artery = null;
      controller_ui.createButton(p1, func_build_road_local, img_build_road_local);
      controller_ui.createButton(p2, func_build_road_collector, img_build_road_collector);
      controller_ui.createButton(p2, func_build_road_artery, img_build_road_artery);
    }

    return E_UI;

  })(TSAG.E_Super);

}).call(this);
