// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Path_Element = (function(superClass) {
    extend(Path_Element, superClass);

    function Path_Element(model, polyline, width, fill_color) {
      Path_Element.__super__.constructor.call(this, model);
      this._polyline = null;
      this._width = null;
    }

    Path_Element.prototype.getLocation = function(percentage) {};

    return Path_Element;

  })(TSAG.Element);

}).call(this);
