// Generated by CoffeeScript 1.11.1

/*
 *
 * Model Interface Class.
 * This specifies properties of all element objects.
 *
 * Written by Bryce Summers on 10.23.2017
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Test_Place = (function(superClass) {
    extend(Test_Place, superClass);

    function Test_Place() {
      var place_model, pts, square, square_mesh, square_place;
      Test_Place.__super__.constructor.call(this, new TSAG.Place_Model());
      place_model = new TSAG.Place_Model();
      pts = [new BDS.Point(0, 0), new BDS.Point(100, 0), new BDS.Point(100, 100), new BDS.Point(0, 100)];
      square = new BDS.Polyline(true, pts);
      square_mesh = EX.Visual_Factory.newPolygon(square, new THREE.Color(1, 0, 0));
      square_place = new TSAG.Place_Element(place_model);
      square_place.setVisualRepresentation(square_mesh);
      this.addPlace(square_place);
    }

    return Test_Place;

  })(TSAG.Place_Element);

}).call(this);
