// Generated by CoffeeScript 1.11.1

/*
 *
 * GUI Set.
 *
 * This class may someday use AABB's to optimize clicks and handling of GUI button elements.
 *
 */

(function() {


}).call(this);

//# sourceMappingURL=gui_layer.js.map
