// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.S_Vertex = (function() {
    function S_Vertex() {
      this._edges = [];
      this._element = null;
    }

    S_Vertex.prototype.addEdge = function(edge) {
      return this._edges.push(edge);
    };

    S_Vertex.prototype.setElement = function(element) {
      return this._element = element;
    };

    S_Vertex.prototype.getElement = function() {
      return this._element;
    };

    return S_Vertex;

  })();

  TSAG.S_Edge = (function() {
    function S_Edge() {
      this._v0 = null;
      this._v1 = null;
      this.element = null;
    }

    S_Edge.prototype.getStartVert = function() {
      return this._v0;
    };

    S_Edge.prototype.getEndVert = function() {
      return this._v1;
    };

    S_Edge.prototype.setStartVert = function(v0) {
      return this._v0 = v0;
    };

    S_Edge.prototype.setEndVert = function(v1) {
      return this._v1 = v1;
    };

    S_Edge.prototype.setVerts = function(v0, v1) {
      this._v0 = v0;
      return this._v1 = v1;
    };

    S_Edge.prototype.setElement = function(element) {
      return this._element = element;
    };

    S_Edge.prototype.getElement = function() {
      return this._element;
    };

    return S_Edge;

  })();

  TSAG.S_Network_Topology = (function() {
    function S_Network_Topology() {
      this._bvh_needs_update = true;
      this._bvh = null;
      this._vertices = [];
      this._edges = [];
    }

    S_Network_Topology.prototype.newVertex = function() {
      var vert;
      vert = new TSAG.S_Vertex();
      this._vertices.push(vert);
      return vert;
    };

    S_Network_Topology.prototype.newEdge = function() {
      var edge;
      edge = new TSAG.S_Edge();
      this._edges.push(edge);
      return edge;
    };

    return S_Network_Topology;

  })();

}).call(this);
