// Generated by CoffeeScript 1.11.1

/*
 *
 * Model Interface Class.
 * This specifies properties of all element objects.
 *
 * Written by Bryce Summers on 10.23.2017
 */

(function() {
  TSAG.Model = (function() {
    function Model(_element) {
      this._element = _element;
      this._ui = null;
    }

    Model.prototype.listNeighbors = function() {
      return console.log("Please Implement me!");
    };

    Model.prototype.heuristicTo = function(element) {
      return console.log("Please Implement me!");
    };

    Model.prototype.getLocation = function() {
      return console.log("Please Implement me!");
    };

    Model.prototype.getElement = function() {
      return this._element;
    };

    return Model;

  })();

}).call(this);
