// Generated by CoffeeScript 1.11.1

/*
    Written by Bryce Summers on 10.23.2017

    A Model for a current camera view of a place.
    These are preserved between visits to places.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Camera_Model = (function(superClass) {
    extend(Camera_Model, superClass);

    function Camera_Model() {}

    Camera_Model.prototype.buildModel = function() {};

    return Camera_Model;

  })(TSAG.Model);

}).call(this);
