// Generated by CoffeeScript 1.11.1

/*
    Written by Bryce Summers on 10.23.2017
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Junction_Model = (function(superClass) {
    extend(Junction_Model, superClass);

    function Junction_Model() {
      this._configurations = null;
    }

    Junction_Model.prototype.buildModel = function() {};

    return Junction_Model;

  })(TSAG.Model);

}).call(this);
