// Generated by CoffeeScript 1.11.1

/*
    Written by Bryce Summers on 10.23.2017
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Path_Model = (function(superClass) {
    extend(Path_Model, superClass);

    function Path_Model(capacity, transversal_cost) {
      this._capacity = capacity;
      this._occupancy = 0;
      this._cost = transversal_cost;
      this.destination = null;
      this.last_object = null;
    }

    Path_Model.prototype.isClear = function() {
      return this._occupancy === 0;
    };

    return Path_Model;

  })(TSAG.Model);

}).call(this);
