// Generated by CoffeeScript 1.11.1

/*
    Written by Bryce Summers on 10.23.2017

    A model for the statistics of an object.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.Statistics_Model = (function(superClass) {
    extend(Statistics_Model, superClass);

    function Statistics_Model() {}

    Statistics_Model.prototype.buildModel = function() {};

    return Statistics_Model;

  })(TSAG.Model);

}).call(this);
