// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.I_All_Main = (function() {
    function I_All_Main(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      this._mouse_input = new TSAG.I_Mouse_Main(this.scene, this.camera);
    }

    I_All_Main.prototype.mouse_down = function(event) {
      return this._mouse_input.mouse_down(event);
    };

    I_All_Main.prototype.mouse_up = function(event) {
      return this._mouse_input.mouse_up(event);
    };

    I_All_Main.prototype.mouse_move = function(event) {
      return this._mouse_input.mouse_move(event);
    };

    return I_All_Main;

  })();

}).call(this);
