// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.I_Mouse_Highlight = (function() {
    function I_Mouse_Highlight(e_scene, camera) {
      this.e_scene = e_scene;
      this.camera = camera;
      this.network = this.e_scene.getNetwork();
      this.previous_elements = [];
    }

    I_Mouse_Highlight.prototype.isIdle = function() {
      return true;
    };

    I_Mouse_Highlight.prototype.finish = function() {
      var prev_elem, results;
      results = [];
      while (this.previous_elements.length > 0) {
        prev_elem = this.previous_elements.pop();
        results.push(prev_elem.revertFillColor());
      }
      return results;
    };

    I_Mouse_Highlight.prototype.mouse_down = function(event) {
      if (this.previous_elements.length > 0) {

        /*
        @network.removeVisual(@previous_element.getVisual())
        @network.removeCollisionPolygon(@previous_element.getCollisionPolygon())
        #@network.removeTopology
         */
      }
    };

    I_Mouse_Highlight.prototype.mouse_up = function(event) {};

    I_Mouse_Highlight.prototype.mouse_move = function(event) {
      var elem, elems, i, len, results, road;
      this.finish();
      elems = this.network.query_elements_pt(event.x, event.y);
      results = [];
      for (i = 0, len = elems.length; i < len; i++) {
        elem = elems[i];
        if (elem instanceof TSAG.E_Road) {
          road = elem;
          road.setFillColor(TSAG.style.highlight);
          results.push(this.previous_elements.push(road));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    return I_Mouse_Highlight;

  })();

}).call(this);

//# sourceMappingURL=i_mouse_highlight.js.map
