// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.I_Mouse_Stats_Overlays = (function() {
    function I_Mouse_Stats_Overlays(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      this.overlays = this.scene.getOverlays();
      this.view = this.overlays.getVisual();
      this.network = this.scene.getNetwork();
      this.previous_elements = [];
    }

    I_Mouse_Stats_Overlays.prototype.isIdle = function() {
      return true;
    };

    I_Mouse_Stats_Overlays.prototype.finish = function() {
      var prev_elem, results;
      results = [];
      while (this.previous_elements.length > 0) {
        prev_elem = this.previous_elements.pop();
        results.push(prev_elem.hide_stats(this.view));
      }
      return results;
    };

    I_Mouse_Stats_Overlays.prototype.mouse_down = function(event) {
      if (this.previous_elements.length > 0) {

        /*
        @network.removeVisual(@previous_element.getVisual())
        @network.removeCollisionPolygon(@previous_element.getCollisionPolygon())
        #@network.removeTopology
         */
      }
    };

    I_Mouse_Stats_Overlays.prototype.mouse_up = function(event) {};

    I_Mouse_Stats_Overlays.prototype.mouse_move = function(event) {
      var elem;
      this.finish();
      elem = this.network.query_area_elements_pt(new BDS.Point(event.x, event.y));
      if (elem !== null) {
        elem.display_stats(this.view);
        return this.previous_elements.push(elem);
      }
    };

    return I_Mouse_Stats_Overlays;

  })();

}).call(this);
