// Generated by CoffeeScript 1.11.1
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.I_Mouse_Main = (function(superClass) {
    extend(I_Mouse_Main, superClass);

    function I_Mouse_Main(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      I_Mouse_Main.__super__.constructor.call(this);
      this._create_cursor();
      this.road_build_controller = new TSAG.I_Mouse_Build_Road(this.scene, this.camera);
      this.highlight_controller = new TSAG.I_Mouse_Highlight(this.scene, this.camera);
      this.stats_controller = new TSAG.I_Mouse_Stats_Overlays(this.scene, this.camera);
      this.ui_controller = new TSAG.UI_Controller(this.scene, this.camera);
      this._current_mouse_input_controller = this.stats_controller;
      this.state = "idle";
      this._min_dist = 10;
    }

    I_Mouse_Main.prototype.getRoadBuild = function() {
      return this.road_build_controller;
    };

    I_Mouse_Main.prototype.getRoadDestroy = function() {
      return this.road_destroy_controller;
    };

    I_Mouse_Main.prototype.getHighlight = function() {
      return this.highlight_controller;
    };

    I_Mouse_Main.prototype.getStats = function() {
      return this.stats_controller;
    };

    I_Mouse_Main.prototype.deactivateTools = function() {
      this.road_build_controller.setActive(false);
      this.highlight_controller.setActive(false);
      return this.stats_controller.setActive(false);
    };


    /*------------------------------------
      Internal Helper Functions.
    #--------------------------------------
     */

    I_Mouse_Main.prototype._create_cursor = function() {
      var h, mesh, mesh_factory, overlays, params, scale, w;
      mesh_factory = new TSAG.Unit_Meshes();
      params = {
        color: TSAG.style.cursor_circle_color
      };
      mesh = mesh_factory.newCircle(params);
      scale = TSAG.style.cursor_circle_radius;
      mesh.position.z = TSAG.style.cursor_circle_z;
      w = scale;
      h = scale;
      scale = mesh.scale;
      scale.x = w;
      scale.y = h;
      overlays = this.scene.getOverlays();
      overlays.addPermanentVisual(mesh);
      return this.pointer = mesh;
    };

    I_Mouse_Main.prototype.mouse_down = function(event) {
      if (this._current_mouse_input_controller !== this.road_build_controller && this._current_mouse_input_controller.isIdle()) {
        this.switchController(this.road_build_controller);
      }
      return this._current_mouse_input_controller.mouse_down(event);
    };

    I_Mouse_Main.prototype.mouse_up = function(event) {
      return this._current_mouse_input_controller.mouse_up(event);
    };

    I_Mouse_Main.prototype.mouse_move = function(event) {
      var pos;
      if (this._current_mouse_input_controller !== this.highlight_controller && this._current_mouse_input_controller.isIdle()) {
        this.switchController(this.stats_controller);
      }
      pos = this.pointer.position;
      pos.x = event.x;
      pos.y = event.y;
      return this._current_mouse_input_controller.mouse_move(event);
    };

    I_Mouse_Main.prototype.switchController = function(controller) {
      this._current_mouse_input_controller.finish();
      return this._current_mouse_input_controller = controller;
    };

    return I_Mouse_Main;

  })(BDS.Interface_Controller_All);

}).call(this);
