// Generated by CoffeeScript 1.11.1

/*

Time Input Controller.

Written by Bryce Summmers on 1 - 31 - 2017.
 */

(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TSAG.I_Time_Main = (function(superClass) {
    extend(I_Time_Main, superClass);

    function I_Time_Main(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      I_Time_Main.__super__.constructor.call(this);
      this.add_time_input_controller(new TSAG.I_Time_Generate_Cars(this.scene, this.camera));
    }

    return I_Time_Main;

  })(TSAG.Input_Controller);

}).call(this);
