// Generated by CoffeeScript 1.11.1

/*

Building Rotation Time Controller.

Written by Bryce Summmers on 1 - 31 - 2017.

 - A Test time controller that takes every building in the scene and rotates it by a steady rate.
 */

(function() {
  TSAG.I_Time_Generate_Cars = (function() {
    function I_Time_Generate_Cars(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      this.time_count = 0.0;
      this.time_step = 1000.0;
    }

    I_Time_Generate_Cars.prototype.time = function(dt) {
      var car, destroyed, i, j, k, lane, lanes, len, len1, len2, network, road, roads, x, y;
      this.time_count += dt;
      this.gen_cars = false;
      if (this.time_count > this.time_step) {
        this.time_count = (this.time_count % this.time_step) - this.time_step;
        this.gen_cars = true;
      }
      network = this.scene.getNetwork();
      roads = network.getRoads();
      for (i = 0, len = roads.length; i < len; i++) {
        road = roads[i];
        lanes = road.getLanes();
        for (j = 0, len1 = lanes.length; j < len1; j++) {
          lane = lanes[j];
          if (this.gen_cars) {
            x = TSAG.style.road_offset_amount;
            y = TSAG.style.road_offset_amount;
            car = new TSAG.E_Car(new THREE.Vector3(x, y, 1));
            this.scene.addVisual(car.getVisual());
            lane.addCar(car);
          }
          destroyed = lane.moveCars();
          for (k = 0, len2 = destroyed.length; k < len2; k++) {
            car = destroyed[k];
            this.scene.removeVisual(car.getVisual());
          }
        }
      }
    };

    return I_Time_Generate_Cars;

  })();

}).call(this);
