// Generated by CoffeeScript 1.11.1
(function() {
  TSAG.I_Tool_Controller = (function() {
    function I_Tool_Controller(scene, camera) {
      this.scene = scene;
      this.camera = camera;
      this.active = true;
    }

    I_Tool_Controller.prototype.setActive = function(val) {
      return this.active = val;
    };

    I_Tool_Controller.prototype.isActive = function() {
      return this.active;
    };

    return I_Tool_Controller;

  })();

}).call(this);
