// Generated by CoffeeScript 1.11.1

/*
 *
 * Representation Class.
 *
 * Written by Bryce Summers on 10.23.2017
 *
 * Provides the universal functionality for visually representing and interactively querying elements.
 */

(function() {
  TSAG.Representation = (function() {
    function Representation(_model) {
      this._model = _model;
      this._view = new Object3D();
      this._bvh = new BDS.BVH2D();
      this._collision_polygon = null;
    }

    Representation.prototype.getVisual = function() {
      return this._view;
    };

    Representation.prototype.addVisual = function(subview) {
      return this._view.add(subview);
    };

    Representation.prototype.removeVisual = function(subview) {
      return this._view.remove(subview);
    };

    Representation.prototype.addCollisionPolygons = function(polygons) {
      var aPolygon, i, len, results;
      results = [];
      for (i = 0, len = polygons.length; i < len; i++) {
        aPolygon = polygons[i];
        results.push(this.addCollisionPolygon(aPolygon));
      }
      return results;
    };

    Representation.prototype.addCollisionPolygon = function(polygon) {
      return this._bvh.add(polygon);
    };

    Representation.prototype.removeCollisionPolygons = function(polygons) {
      var aPolygon, i, len, results;
      results = [];
      for (i = 0, len = polygons.length; i < len; i++) {
        aPolygon = polygons[i];
        results.push(this.removeCollisionPolygon(aPolygon));
      }
      return results;
    };

    Representation.prototype.removeCollisionPolygon = function(polygon) {
      return this._bvh.remove(polygon);
    };

    Representation.prototype.generateBVH = function() {
      var polylines;
      polylines = this._to_collision_polygons();
      return this._bvh = new BDS.BVH2D(polylines);
    };

    Representation.prototype.generateCollisionPolygon = function() {
      this._collision_polygon = this._bvh.toBoundingBox().toPolyline();
      this._collision_polygon.setAssociatedData(this);
      return this._collision_polygon;
    };

    Representation.prototype.getCollisionPolygon = function() {
      if (this._collision_polygon === null) {
        this.generateCollisionPolygon();
      }
      return this._collision_polygon;
    };

    Representation.prototype._to_collision_polygons = function(output) {
      var a, b, c, face, faces, geometry, i, j, len, len1, localToWorld, mesh, mesh_list, obj, polyline, polyline_list, vertices;
      obj = this._view;
      mesh_list = this._to_mesh_list(obj);
      polyline_list = [];
      if (output !== void 0) {
        polyline_list = output;
      }
      for (i = 0, len = mesh_list.length; i < len; i++) {
        mesh = mesh_list[i];
        geometry = mesh.geometry;
        vertices = geometry.vertices;
        faces = geometry.faces;
        localToWorld = mesh.matrixWorld;
        for (j = 0, len1 = faces.length; j < len1; j++) {
          face = faces[j];
          a = vertices[face.a].clone();
          b = vertices[face.b].clone();
          c = vertices[face.c].clone();
          a.applyMatrix4(localToWorld);
          b.applyMatrix4(localToWorld);
          c.applyMatrix4(localToWorld);
          a = this._vector_to_point(a);
          b = this._vector_to_point(b);
          c = this._vector_to_point(c);
          polyline = new BDS.Polyline(true, [a, b, c]);
          polyline.setAssociatedData(this);
          polyline_list.push(polyline);
        }
      }
      return polyline_list;
    };

    Representation.prototype._vector_to_point = function(vec) {
      return new BDS.Point(vec.x, vec.y, vec.z);
    };

    Representation.prototype._to_mesh_list = function(obj) {
      var add_output, output;
      output = [];
      add_output = function(o) {
        if (o.geometry) {
          return output.push(o);
        }
      };
      obj.traverse(add_output);
      return output;
    };

    Representation.prototype.setFillColor = function(c) {
      var err;
      err = new Error("This method should be overriden in a subclass.");
      console.log(err.stack);
      debugger;
      throw err;
    };

    Representation.prototype.revertFillColor = function() {
      var err;
      err = new Error("This method should be overriden in a subclass.");
      console.log(err.stack);
      debugger;
      throw err;
    };

    Representation.prototype.setPosition = function(position) {
      var z;
      z = this._view.position.z;
      this._view.position.copy(position.clone());
      return this._view.position.z = z;
    };

    Representation.prototype.setRotation = function(rotation_z) {
      return this._view.rotation.z = rotation_z;
    };

    Representation.prototype.getRotation = function() {
      return this._view.rotation.z;
    };

    Representation.prototype.setScale = function(scale) {
      return this._view.scale.copy(scale.clone());
    };

    Representation.prototype.getPosition = function() {
      return this._view.position.clone();
    };

    Representation.prototype.containsPt = function(pt) {
      return this._bvh.query_point(pt) !== null;
    };

    return Representation;

  })();

}).call(this);
